ARG ELK_VERSION

# https://github.com/elastic/logstash-docker
#FROM docker-elk_logstash
FROM docker.elastic.co/logstash/logstash:7.5.1

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
